components {
  id: "ball"
  component: "/main/entities/ball/ball.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 0.01\n"
  "friction: 0.0\n"
  "restitution: 1.0\n"
  "group: \"ball\"\n"
  "mask: \"wall\"\n"
  "mask: \"line\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 10.0\n"
  "}\n"
  "bullet: true\n"
  ""
}
