-- main/entities/line/line_segment.script

go.property("life_time", 2.5) -- Линия исчезает через 2.5 секунды

function init(self)
	-- Автоматическое уничтожение сегмента по таймеру
	timer.delay(self.life_time, false, function()
		go.delete()
	end)
end

function on_message(self, message_id, message, sender)
	-- Если шар коснулся линии — можно сразу ее уничтожить (эффект одноразового батута)
	if message_id == hash("collision_response") and message.other_group == hash("ball") then
		go.delete()
	end
end